name: "Deploy"

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment"
        type: string
        required: true
      version:
        description: "Version"
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          # Add your deployment steps here