name: Release please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release call
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.PAT }}

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    with:
      environment: prod
      version: ${{ needs.release-please.outputs.tag_name }}
      
  
          