name: Scan

on:
  push:
    branches: ['release-please--*']
  
permissions:
  id-token: write
  contents: read
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - name: Scan
        run: |
          echo "Scanning"
          git describe --tags --always